# AppVeyor configuration for AppVeyor project "primordialmachine".
clone_depth: 1

# Build worker image (VM template).
image: Visual Studio 2022

# Build on pushes to all branches.
#branches:
#  only:
#    - main
#    - develop

# Do not build on tag pushes.
skip_tags: true

# Build platform "x64" and "Win32".
platform:
    - x64
    - Win32

# Build configurations.
configuration:
    - Release
    - Debug
    - MinSizeRel
    - RelWithDebInfo

install:
    # Enable long paths.
    - ps: |
        Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
        Start-Sleep -s 10
        Restart-Computer -Force
        Start-Sleep -s 10
    # Download and install CMake.
    - set CMAKE_URL="https://cmake.org/files/v3.29/cmake-3.29.0-windows-x86_64.zip"
    - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
    - 7z x cmake.zip -oC:\projects\deps > nul
    - move C:\projects\deps\cmake-* C:\projects\deps\cmake # Move to a version-agnostic directory
    - set PATH=C:\projects\deps\cmake\bin;%PATH%
    - cmake --version
    # Install dependencies.
    - ps: |
        Write-Host "APPVEYOR_BUILD_FOLDER:   ${env:APPVEYOR_BUILD_FOLDER}"
        ${env:INSTALL_DEPENDENCIES_SCRIPT}="${env:APPVEYOR_BUILD_FOLDER}/install-dependencies.ps1" 
        if (Test-Path -Path ${env:INSTALL_DEPENDENCIES_SCRIPT}) {
            Write-Host "${env:INSTALL_DEPENDENCIES_SCRIPT} found"          
        } else {
            Write-Host "${env:INSTALL_DEPENDENCIES_SCRIPT} NOT found"
        }
        . "${env:INSTALL_DEPENDENCIES_SCRIPT}"

# Generate solution and project files.
before_build:
    # Create configuration.
    - ps: |
        # The name of the CMake generator, for example "Visual Studio 17 2022".
        ${env:CMAKE_GENERATOR_NAME}="Visual Studio 17 2022" ;

        # The name of the release, for example "michaelheilmann.com-windows-debug-10.1.9".
        ${env:RELEASE_NAME}="michaelheilmann.com-windows-$(${env:APPVEYOR_REPO_BRANCH})-v$(${env:APPVEYOR_BUILD_VERSION}.ToLower())"

        # The name of the zip file, for example "michaelheilmann.com-debug-windows-x86-debug-10.1.9.zip".
        ${env:ARCHIVE_FILENAME}="michaelheilmann.com-${env:APPVEYOR_REPO_BRANCH}";
        ${env:ARCHIVE_FILENAME}="${env:ARCHIVE_FILENAME}-windows"

        # The name of the CMake architecture, for example "Win32" or "x64".
        ${env:CMAKE_ARCHITECTURE_NAME}=${env:PLATFORM}

        if (${env:PLATFORM} -eq 'Win32') {
          ${env:ARCHIVE_FILENAME}="${env:ARCHIVE_FILENAME}-x86"
        } elseif(${env:PLATFORM} -eq 'x64') {
          ${env:ARCHIVE_FILENAME}="${env:ARCHIVE_FILENAME}-x64"
        } else {
          throw "unsupported platform ${env:PLATFORM}";
        }

        ${env:ARCHIVE_FILENAME}="${env:ARCHIVE_FILENAME}-$(${env:CONFIGURATION}.ToLower())-v$(${env:APPVEYOR_BUILD_VERSION}.ToLower())";
        ${env:ARCHIVE_FILENAME}="${env:ARCHIVE_FILENAME}.zip";
    # Emit the configuration.
    - ps: |
        Write-Host "Release Name:           ${env:RELEASE_NAME}";
        Write-Host "AppVeyor Platform:      ${env:PLATFORM}";
        Write-Host "AppVeyor Configuration: ${env:CONFIGURATION}";
        Write-Host "Zip File Name:          ${env:ARCHIVE_FILENAME}";
        Write-Host "CMake Generator:        ${env:CMAKE_GENERATOR_NAME}"
        Write-Host "CMake Architecture:     ${env:CMAKE_ARCHITECTURE_NAME}"
    # Generate build files.
    - ps: |
        cmake -G ${env:CMAKE_GENERATOR_NAME} -A ${env:CMAKE_ARCHITECTURE_NAME} -D"Arcadia.Audials.OpenAl.Enabled"=TRUE -D"Arcadia.Visuals.OpenGl.Enabled"=TRUE CMakeLists.txt

build:
    parallel: true # enable MSBuild parallel builds
    project: Arcadia.sln # path to Visual Studio solution or project

after_build:
    - ps: New-Item ${env:APPVEYOR_BUILD_FOLDER}\.keepme -type file
    - ps: 7z a ${env:ARCHIVE_FILENAME} ${env:APPVEYOR_BUILD_FOLDER}\.keepme

test_script:
    - ps: ctest --output-junit test-results-${env:APPVEYOR_JOB_ID}.xml -C ${env:CONFIGURATION}
    - ps: |
        $webClient = New-Object 'System.Net.WebClient'
        $webClient.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test-results-${env:APPVEYOR_JOB_ID}.xml))

# If one matrix entry fails, all entries fails (https://www.appveyor.com/docs/build-configuration#failing-strategy).
matrix:
    fast_finish: true

artifacts:
    - path: $(ARCHIVE_FILENAME)
      name: $(ARCHIVE_FILENAME)

deploy:
    release: $(RELEASE_NAME)
    tag: $(RELEASE_NAME)
    description: 'michaelheilmann.com $(APPVEYOR_REPO_BRANCH) branch v$(APPVEYOR_BUILD_VERSION)'
    provider: GitHub
    auth_token:
        secure: iTg7jon0UCvoGT5y2flVxKbuZIM0cCf+3cKmhb811umlbh9zHOtvJQjEqDU53XDT8/SE5zreMGYwnShZDpovMZRmpiuTdlQD9Y0hjKw1a+QBZguyWOpmttY9hv8E5FFq # encrypted token from GitHub
        artifact: $(ARCHIVE_FILENAME) # upload the artifact
    draft: true
    prerelease: false
    force_update: true
